export const embeddedReferenceRun = Object.freeze([
  { line: "src/electron", progress: 3 },
  { line: "src", progress: 6 },
  { line: "src/buildtools/win:gn/gn/windows-amd64", progress: 6 },
  { line: "src/buildtools/third_party/libunwind/trunk", progress: 7 },
  { line: "src/buildtools/third_party/libc++abi/trunk", progress: 7 },
  { line: "src/buildtools/clang_format/script", progress: 7 },
  { line: "src/third_party/nan", progress: 7 },
  {
    line: "src/chrome/browser/resources/media_router/extension/src",
    progress: 7,
  },
  { line: "src/buildtools/third_party/libc++/trunk", progress: 7 },
  { line: "src/third_party/squirrel.mac", progress: 8 },
  { line: "src/chrome/test/data/xr/webvr_info", progress: 9 },
  { line: "src/chrome/test/data/perf/frame_rate/content", progress: 9 },
  { line: "src/chrome/test/data/perf/canvas_bench", progress: 9 },
  {
    line: "src/third_party/blink/web_tests/wpt_internal/webgpu/third_party/glslang_js:chromium/third_party/glslang_js",
    progress: 9,
  },
  { line: "src/media/cdm/api", progress: 9 },
  { line: "src/net/third_party/quiche/src", progress: 9 },
  { line: "src/third_party/SPIRV-Tools/src", progress: 9 },
  { line: "src/third_party/squirrel.mac/vendor/Mantle", progress: 10 },
  { line: "src/third_party/breakpad/breakpad", progress: 11 },
  { line: "src/third_party/ced/src", progress: 11 },
  { line: "src/third_party/catapult", progress: 11 },
  { line: "src/third_party/angle", progress: 11 },
  { line: "src/third_party/squirrel.mac/vendor/ReactiveObjC", progress: 11 },
  { line: "src/third_party/cld_3/src", progress: 11 },
  { line: "src/third_party/boringssl/src", progress: 11 },
  { line: "src/third_party/electron_node", progress: 11 },
  { line: "src/third_party/colorama/src", progress: 12 },
  { line: "src/third_party/crc32c/src", progress: 12 },
  { line: "src/third_party/dawn", progress: 12 },
  { line: "src/third_party/dav1d/libdav1d", progress: 13 },
  { line: "src/third_party/dom_distiller_js/dist", progress: 13 },
  { line: "src/third_party/depot_tools", progress: 13 },
  { line: "src/third_party/emoji-segmenter/src", progress: 13 },
  { line: "src/third_party/devtools-frontend/src", progress: 13 },
  { line: "src/third_party/expat/src", progress: 14 },
  { line: "src/third_party/flatbuffers/src", progress: 14 },
  { line: "src/third_party/flac", progress: 14 },
  { line: "src/third_party/ffmpeg", progress: 14 },
  { line: "src/third_party/glslang/src", progress: 15 },
  { line: "src/third_party/freetype/src", progress: 15 },
  { line: "src/third_party/glfw/src", progress: 15 },
  { line: "src/third_party/googletest/src", progress: 15 },
  { line: "src/third_party/gperf", progress: 16 },
  { line: "src/third_party/hunspell_dictionaries", progress: 16 },
  { line: "src/third_party/grpc/src", progress: 16 },
  { line: "src/third_party/harfbuzz-ng/src", progress: 16 },
  { line: "src/third_party/jsoncpp/source", progress: 16 },
  { line: "src/third_party/leveldatabase/src", progress: 16 },
  { line: "src/third_party/icu", progress: 16 },
  { line: "src/third_party/libFuzzer/src", progress: 17 },
  { line: "src/third_party/libaddressinput/src", progress: 17 },
  { line: "src/third_party/libavif/src", progress: 17 },
  { line: "src/third_party/libaom/source/libaom", progress: 17 },
  { line: "src/third_party/libgav1/src", progress: 17 },
  { line: "src/third_party/libgifcodec", progress: 18 },
  { line: "src/third_party/libphonenumber/dist", progress: 18 },
  { line: "src/third_party/libjpeg_turbo", progress: 18 },
  { line: "src/third_party/libprotobuf-mutator/src", progress: 18 },
  { line: "src/third_party/libsrtp", progress: 19 },
  { line: "src/third_party/libyuv", progress: 19 },
  { line: "src/third_party/libvpx/source/libvpx", progress: 19 },
  { line: "src/third_party/libwebm/source", progress: 19 },
  { line: "src/third_party/lighttpd", progress: 19 },
  { line: "src/third_party/nasm", progress: 19 },
  { line: "src/third_party/nearby/src", progress: 19 },
  { line: "src/third_party/openh264/src", progress: 20 },
  { line: "src/third_party/openscreen/src", progress: 20 },
  { line: "src/third_party/pefile", progress: 20 },
  { line: "src/third_party/pdfium", progress: 20 },
  {
    line: "src/third_party/shaka-player/dist:chromium/third_party/shaka-player",
    progress: 20,
  },
  { line: "src/third_party/perfetto", progress: 20 },
  { line: "src/third_party/perl", progress: 21 },
  { line: "src/third_party/quic_trace/src", progress: 21 },
  { line: "src/third_party/pywebsocket3/src", progress: 21 },
  { line: "src/third_party/re2/src", progress: 21 },
  { line: "src/third_party/shaderc/src", progress: 22 },
  { line: "src/third_party/securemessage/src", progress: 22 },
  { line: "src/third_party/smhasher/src", progress: 22 },
  { line: "src/third_party/skia", progress: 22 },
  { line: "src/third_party/snappy/src", progress: 22 },
  { line: "src/third_party/spirv-cross/spirv-cross", progress: 22 },
  { line: "src/third_party/spirv-headers/src", progress: 22 },
  { line: "src/third_party/sqlite/src", progress: 23 },
  { line: "src/third_party/ukey2/src", progress: 23 },
  { line: "src/third_party/tint/src", progress: 23 },
  { line: "src/third_party/swiftshader", progress: 23 },
  {
    line: "src/tools/luci-go:infra/tools/luci/isolate/${platform}",
    progress: 23,
  },
  {
    line: "src/tools/luci-go:infra/tools/luci/isolated/${platform}",
    progress: 23,
  },
  {
    line: "src/tools/luci-go:infra/tools/luci/swarming/${platform}",
    progress: 23,
  },
  { line: "src/third_party/usrsctp/usrsctplib", progress: 23 },
  {
    line: "src/tools/skia_goldctl/win:skia/tools/goldctl/windows-amd64",
    progress: 23,
  },
  { line: "src/third_party/vulkan_memory_allocator", progress: 23 },
  { line: "src/third_party/webdriver/pylib", progress: 24 },
  { line: "src/third_party/webgl/src", progress: 24 },
  { line: "src/third_party/webgpu-cts/src", progress: 24 },
  { line: "src/third_party/wuffs/src", progress: 24 },
  { line: "src/tools/page_cycler/acid3", progress: 24 },
  { line: "src/third_party/webrtc", progress: 24 },
  { line: "src/tools/swarming_client", progress: 24 },
  {
    line: "src\\third_party\\angle\\third_party\\VK-GL-CTS\\src",
    progress: 25,
  },
  { line: "src\\third_party\\angle\\third_party\\glmark2\\src", progress: 25 },
  {
    line: "src\\third_party\\angle\\third_party\\rapidjson\\src",
    progress: 25,
  },
  { line: "src/v8", progress: 25 },
  {
    line: "src\\third_party\\angle\\third_party\\vulkan-headers\\src",
    progress: 25,
  },
  {
    line: "src\\third_party\\angle\\third_party\\vulkan-tools\\src",
    progress: 25,
  },
  {
    line: "src\\third_party\\angle\\third_party\\vulkan-loader\\src",
    progress: 26,
  },
  {
    line: "src\\third_party\\angle\\third_party\\vulkan-validation-layers\\src",
    progress: 26,
  },
  {
    line: "src\\third_party\\openscreen\\src\\third_party\\tinycbor\\src",
    progress: 26,
  },
  {
    line: "running 'python3 src/electron/script/apply_all_patches.py src/electron/patches/config.json'",
    progress: 66,
  },
  { line: "Applying: add_realloc.patch", progress: 75 },
  { line: "Applying: build_gn.patch", progress: 75 },
  { line: "Applying: dcheck.patch", progress: 75 },
  { line: "Applying: accelerator.patch", progress: 75 },
  { line: "Applying: blink_file_path.patch", progress: 75 },
  { line: "Applying: blink_local_frame.patch", progress: 75 },
  { line: "Applying: blink_world_context.patch", progress: 75 },
  { line: "Applying: can_create_window.patch", progress: 75 },
  { line: "Applying: disable_hidden.patch", progress: 75 },
  { line: "Applying: dom_storage_limits.patch", progress: 75 },
  { line: "Applying: render_widget_host_view_base.patch", progress: 75 },
  { line: "Applying: render_widget_host_view_mac.patch", progress: 75 },
  { line: "Applying: thread_capabilities.patch", progress: 75 },
  { line: "Applying: webview_cross_drag.patch", progress: 75 },
  { line: "Applying: gin_enable_disable_v8_platform.patch", progress: 75 },
  {
    line: "Applying: blink-worker-enable-csp-in-file-scheme.patch",
    progress: 75,
  },
  { line: "Applying: disable-redraw-lock.patch", progress: 75 },
  { line: "Applying: v8_context_snapshot_generator.patch", progress: 75 },
  { line: "Applying: boringssl BUILD.gn", progress: 75 },
  { line: "Applying: pepper plugin support", progress: 75 },
  { line: "Applying: no_cache_storage_check.patch", progress: 75 },
  { line: "Applying: blink_fix_prototype_assert.patch", progress: 75 },
  { line: "Applying: gtk_visibility.patch", progress: 75 },
  { line: "Applying: sysroot.patch", progress: 75 },
  { line: "Applying: mas_blink_no_private_api.patch", progress: 75 },
  { line: "Applying: mas_no_private_api.patch", progress: 75 },
  { line: "Applying: resource_file_conflict.patch", progress: 75 },
  { line: "Applying: scroll_bounce_flag.patch", progress: 75 },
  { line: "Applying: mas-cfisobjc.patch", progress: 75 },
  { line: "Applying: mas-cgdisplayusesforcetogray.patch", progress: 75 },
  { line: "Applying: mas-audiodeviceduck.patch", progress: 75 },
  { line: "Applying: mas_disable_remote_layer.patch", progress: 75 },
  { line: "Applying: mas_disable_remote_accessibility.patch", progress: 75 },
  { line: "Applying: mas_disable_custom_window_frame.patch", progress: 75 },
  { line: "Applying: chrome_key_systems.patch", progress: 75 },
  { line: "Applying: add DidInstallConditionalFeatures", progress: 75 },
  { line: "Applying: ssl_security_state_tab_helper.patch", progress: 75 },
  { line: "Applying: desktop_media_list.patch", progress: 75 },
  { line: "Applying: proxy_config_monitor.patch", progress: 75 },
  { line: "Applying: gritsettings_resource_ids.patch", progress: 75 },
  { line: "Applying: isolate_holder.patch", progress: 75 },
  { line: "Applying: notification_provenance.patch", progress: 75 },
  { line: "Applying: content_browser_main_loop.patch", progress: 75 },
  { line: "Applying: dump_syms.patch", progress: 75 },
  { line: "Applying: command-ismediakey.patch", progress: 75 },
  { line: "Applying: printing.patch", progress: 75 },
  { line: "Applying: support_mixed_sandbox_with_zygote.patch", progress: 75 },
  {
    line: "Applying: fix_disable_usage_of_abort_report_np_in_mas_builds.patch",
    progress: 75,
  },
  {
    line: "Applying: fix_disable_usage_of_pthread_fchdir_np_and_pthread_chdir_np_in_MAS.patch",
    progress: 75,
  },
  {
    line: "Applying: fix_disable_usage_of_setapplicationisdaemon_and.patch",
    progress: 75,
  },
  {
    line: "Applying: unsandboxed_ppapi_processes_skip_zygote.patch",
    progress: 75,
  },
  {
    line: "Applying: patch_the_ensure_gn_version_py_script_to_work_on_mac_ci.patch",
    progress: 75,
  },
  { line: "Applying: build_add_electron_tracing_category.patch", progress: 75 },
  { line: "Applying: worker_context_will_destroy.patch", progress: 75 },
  { line: "Applying: frame_host_manager.patch", progress: 75 },
  { line: "Applying: crashpad_pid_check.patch", progress: 75 },
  {
    line: "Applying: remove references to Profile from PreconnectManager",
    progress: 75,
  },
  {
    line: "Applying: network_service_allow_remote_certificate_verification_logic.patch",
    progress: 75,
  },
  {
    line: "Applying: put_back_deleted_colors_for_autofill.patch",
    progress: 75,
  },
  { line: "Applying: disable_color_correct_rendering.patch", progress: 75 },
  {
    line: "Applying: add_contentgpuclient_precreatemessageloop_callback.patch",
    progress: 75,
  },
  {
    line: "Applying: feat: enable picture in picture mode for video players",
    progress: 75,
  },
  { line: "Applying: fix: disabling compositor recycling", progress: 75 },
  {
    line: "Applying: allow new privileges in unsandboxed child processes",
    progress: 75,
  },
  { line: "Applying: expose SetUserAgent on NetworkContext", progress: 75 },
  {
    line: "Applying: feat: add set_theme_source to allow apps to override chromiums internal theme choice",
    progress: 75,
  },
  {
    line: "Applying: add WebMessagePortConverter::EntangleAndInjectMessagePortChannel",
    progress: 75,
  },
  {
    line: 'Applying: Revert "Remove ContentRendererClient::ShouldFork."',
    progress: 75,
  },
  { line: "Applying: ignore_rc_check.patch", progress: 75 },
  {
    line: "Applying: remove usage of incognito APIs in the spellchecker",
    progress: 75,
  },
  {
    line: "Applying: chore: use electron resources not chrome for spellchecker",
    progress: 75,
  },
  { line: "Applying: add TrustedAuthClient to URLLoaderFactory", progress: 75 },
  {
    line: "Applying: feat: allow disabling blink scheduler throttling per RenderView",
    progress: 75,
  },
  {
    line: "Applying: fix: add back virtual methods in AccessiblePaneView",
    progress: 75,
  },
  {
    line: "Applying: fix: use the new MediaPlayPause key listener for internal chrome logic",
    progress: 75,
  },
  {
    line: "Applying: hack plugin response interceptor to point to electron",
    progress: 75,
  },
  {
    line: "Applying: fix: route mouse event navigations through the web_contents delegate",
    progress: 75,
  },
  {
    line: "Applying: feat: add support for overriding the base spellchecker download URL",
    progress: 75,
  },
  {
    line: "Applying: feat: enable off-screen rendering with viz compositor",
    progress: 75,
  },
  {
    line: "Applying: content: allow embedder to prevent locking scheme registry",
    progress: 75,
  },
  {
    line: "Applying: gpu: notify when dxdiag request for gpu info fails",
    progress: 75,
  },
  {
    line: "Applying: feat: allow embedders to add observers on created hunspell dictionaries",
    progress: 75,
  },
  { line: "Applying: feat: add onclose to MessagePort", progress: 75 },
  { line: "Applying: web_contents.patch", progress: 75 },
  { line: "Applying: ui_gtk_public_header.patch", progress: 75 },
  {
    line: "Applying: allow in-process windows to have different web prefs",
    progress: 78,
  },
  {
    line: "Applying: refactor: expose cursor changes to the WebContentsObserver",
    progress: 78,
  },
  { line: "Applying: crash: allow setting more options", progress: 78 },
  {
    line: "Applying: breakpad: treat node processes as browser processes",
    progress: 78,
  },
  { line: "Applying: upload_list: add LoadSync method", progress: 78 },
  {
    line: "Applying: breakpad: allow getting string values for crash keys",
    progress: 78,
  },
  {
    line: "Applying: crash: allow disabling compression on linux",
    progress: 78,
  },
  {
    line: "Applying: Allow setting secondary label via SimpleMenuModel",
    progress: 78,
  },
  {
    line: "Applying: fix: swap global proxies before initializing the windows proxies",
    progress: 78,
  },
  {
    line: "Applying: feat: add streaming-protocol registry to multibuffer_data_source",
    progress: 78,
  },
  {
    line: "Applying: fix: patch out Profile refs in accessibility_ui",
    progress: 78,
  },
  {
    line: "Applying: remove some deps that do not work on arm64",
    progress: 78,
  },
  {
    line: "Applying: fix: check IsSecureEventInputEnabled in constructor before setting SetPasswordInputEnabled to true",
    progress: 78,
  },
  { line: "Applying: skip atk toolchain check", progress: 78 },
  {
    line: "Applying: feat: add hook to notify script ready from WorkerScriptController",
    progress: 78,
  },
  {
    line: "Applying: chore: provide IsWebContentsCreationOverridden with full params",
    progress: 78,
  },
  { line: "Applying: fix: properly honor printing page ranges", progress: 78 },
  { line: "Applying: fix: use electron generated resources", progress: 78 },
  {
    line: "Applying: chore: expose v8 initialization isolate callbacks",
    progress: 78,
  },
  {
    line: "Applying: rename the v8 context snapshot on arm64 macOS builds",
    progress: 78,
  },
  {
    line: "Applying: export gin::V8Platform::PageAllocator for usage outside of the gin platform",
    progress: 78,
  },
  { line: "Applying: expose ripemd160", progress: 78 },
  { line: "Applying: expose aes-{128,256}-cfb", progress: 78 },
  { line: "Applying: add_realloc.patch", progress: 78 },
  { line: "Applying: build_gn.patch", progress: 78 },
  { line: "Applying: expose_mksnapshot.patch", progress: 78 },
  { line: "Applying: dcheck.patch", progress: 78 },
  { line: "Applying: Export symbols needed for Windows build", progress: 78 },
  { line: "Applying: Workaround an undefined symbol error", progress: 78 },
  {
    line: "Applying: Do not export private V8 symbols on Windows",
    progress: 78,
  },
  {
    line: 'Applying: Revert "[cleanup] Switch {OFFSET_OF} to {offsetof} where possible."',
    progress: 78,
  },
  {
    line: "Applying: fix: usage of c++ [[deprecated]] attirbute for older msvc versions",
    progress: 78,
  },
  { line: "Applying: fix: use proper page size for mac arm64", progress: 78 },
  { line: "Applying: Make Module.globalPaths a reference.", progress: 78 },
  {
    line: "Applying: fix: don't create console window when creating process",
    progress: 78,
  },
  {
    line: "Applying: refactor: alter child_process.fork to use execute script with Electron",
    progress: 78,
  },
  { line: "Applying: feat: add uv_loop watcher_queue code", progress: 78 },
  { line: "Applying: feat: initialize asar support", progress: 78 },
  { line: "Applying: Expose `get_linked_module` function", progress: 78 },
  { line: "Applying: fix: expose InternalCallbackScope", progress: 78 },
  { line: "Applying: build: add GN build files", progress: 78 },
  {
    line: "Applying: fix: add default values for 'enable_lto' and 'build_v8_with_gn' in common.gypi",
    progress: 78,
  },
  {
    line: "Applying: feat: add new built_with_electron variable to config.gypi",
    progress: 78,
  },
  {
    line: "Applying: feat: add flags for low-level hooks and exceptions",
    progress: 78,
  },
  {
    line: "Applying: fix: expose tracing::Agent and use tracing::TracingController instead of v8::TracingController",
    progress: 78,
  },
  { line: 'Applying: Pass all globals through "require"', progress: 78 },
  { line: "Applying: FIXME: remove async_id assertion check", progress: 78 },
  { line: "Applying: fixme: Comment trace event macro", progress: 78 },
  {
    line: "Applying: fix: key gen APIs are not available in BoringSSL",
    progress: 78,
  },
  {
    line: "Applying: build: modify js2c.py to allow injection of original-fs and custom embedder JS",
    progress: 78,
  },
  {
    line: "Applying: refactor: allow embedder overriding of internal FS calls",
    progress: 78,
  },
  {
    line: "Applying: chore: prevent / warn non context-aware native modules being loaded",
    progress: 78,
  },
  {
    line: "Applying: chore: read _noBrowserGlobals from global not config",
    progress: 78,
  },
  {
    line: "Applying: build: bring back node_with_ltcg configuration",
    progress: 78,
  },
  { line: 'Applying: Revert "crypto: add oaepLabel option"', progress: 78 },
  {
    line: "Applying: enable 31 bit smis on 64bit arch and ptr compression",
    progress: 78,
  },
  { line: "Applying: fix: use crypto impls for compat", progress: 78 },
  {
    line: "Applying: fix: comment out incompatible crypto modules",
    progress: 78,
  },
  {
    line: "Applying: Update tests after increasing typed array size",
    progress: 78,
  },
  {
    line: "Applying: feat: add implementation of v8::Platform::PostJob",
    progress: 78,
  },
  {
    line: "Applying: fix: -Wincompatible-pointer-types-discards-qualifiers error",
    progress: 78,
  },
  {
    line: "Applying: fix: add v8_enable_reverse_jsargs defines in common.gypi",
    progress: 78,
  },
  {
    line: "Applying: fix: allow preventing InitializeInspector in env",
    progress: 78,
  },
  {
    line: "Applying: src: allow embedders to provide a custom PageAllocator to NodePlatform",
    progress: 78,
  },
  { line: "Applying: build: add GN config", progress: 78 },
  {
    line: "Applying: fix: ensure that self is retained until the RACSignal is complete",
    progress: 78,
  },
  {
    line: "Applying: build: conditionally import EXT headers from framework or from relative path",
    progress: 78,
  },
  {
    line: "Applying: remove some deps that do not work on arm64",
    progress: 78,
  },
  {
    line: "Hook 'python3 src/electron/script/apply_all_patches.py src/electron/patches/config.json' took",
    progress: 78,
  },
  {
    line: 'Hook \'python3 -c \'import os, subprocess; os.chdir(os.path.join("src", "electron")); subprocess.check_call(["python", "script/lib/npx.py", "yarn@1.15.2", "install", "--frozen-lockfile"]);\'\'',
    progress: 81,
  },
  {
    line: "Hook 'vpython.bat src/tools/remove_stale_pyc_files.py src/android_webview/tools src/build/android src/gpu/gles2_conform_support src/infra src/ppapi src/printing src/third_party/blink/renderer/build/scripts src/third_party/blink/tools src/third_party/catapult src/tools'",
    progress: 84,
  },
  {
    line: "Hook 'vpython.bat src/buildtools/ensure_gn_version.py git_revision:e002e68a48d1c82648eadde2f6aafa20d08c36f2'",
    progress: 84,
  },
  {
    line: "Hook 'vpython.bat src/build/vs_toolchain.py update --force'",
    progress: 86,
  },
  {
    line: "Hook 'vpython.bat src/tools/clang/scripts/update.py'",
    progress: 87,
  },
  {
    line: "Hook 'vpython.bat src/tools/clang/scripts/update.py --package=clang-tidy'",
    progress: 88,
  },
  {
    line: "Hook 'vpython.bat src/build/util/lastchange.py -o src/build/util/LASTCHANGE'",
    progress: 88,
  },
  {
    line: "Hook 'vpython.bat src/build/util/lastchange.py -m GPU_LISTS_VERSION --revision-id-only --header src/gpu/config/gpu_lists_version.h'",
    progress: 89,
  },
  {
    line: "Hook 'vpython.bat src/build/util/lastchange.py -m SKIA_COMMIT_HASH -s src/third_party/skia --header src/skia/ext/skia_commit_hash.h'",
    progress: 90,
  },
  {
    line: "Hook 'vpython.bat src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-clang-format -s src/buildtools/win/clang-format.exe.sha1'",
    progress: 90,
  },
  {
    line: "Hook 'vpython.bat src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-browser-clang/rc -s src/build/toolchain/win/rc/win/rc.exe.sha1'",
    progress: 91,
  },
  {
    line: "Hook 'vpython.bat src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --num_threads=4 --bucket chromium-browser-clang/orderfiles -d src/chrome/build'",
    progress: 92,
  },
  {
    line: "Hook 'vpython.bat src/third_party/depot_tools/download_from_google_storage.py --no_resume --directory --recursive --no_auth --num_threads=16 --bucket chromium-apache-win32 src/third_party/apache-win32'",
    progress: 93,
  },
  {
    line: "Hook 'vpython.bat src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth -u --bucket v8-wasm-fuzzer -s src/v8/test/fuzzer/wasm_corpus.tar.gz.sha1'",
    progress: 94,
  },
  {
    line: "Hook 'vpython.bat src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-nodejs/12.14.1 -s src/third_party/node/win/node.exe.sha1'",
    progress: 94,
  },
  {
    line: "Hook 'vpython.bat src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs -s src/third_party/node/node_modules.tar.gz.sha1'",
    progress: 95,
  },
  {
    line: "Hook 'vpython.bat src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --num_threads=4 --bucket chromium-tools-traffic_annotation -d src/tools/traffic_annotation/bin/win32'",
    progress: 96,
  },
  {
    line: "Hook 'vpython.bat src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --num_threads=4 --bucket chromium-binary-patching/zucchini_testdata --recursive -d src/components/zucchini'",
    progress: 97,
  },
  {
    line: "Hook 'vpython.bat src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-ads-detection -s src/third_party/subresource-filter-ruleset/data/UnindexedRules.sha1'",
    progress: 97,
  },
  {
    line: "Hook 'vpython.bat src/tools/update_pgo_profiles.py --target=win32 update --gs-url-base=chromium-optimization-profiles/pgo_profiles'",
    progress: 98,
  },
  {
    line: "Hook 'vpython.bat src/tools/update_pgo_profiles.py --target=win64 update --gs-url-base=chromium-optimization-profiles/pgo_profiles'",
    progress: 99,
  },
]);
