/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Maps patch directory to source tree directory
 */
export type JSONSchemaForElectronPatchesConfigJson = {
  /**
   * Patch directory in the Electron source tree
   */
  patch_dir: string;
  /**
   * Repository directory in the Chromium checkout
   */
  repo: string;
}[];
