/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface JSONSchemaForElectronPatchesConfigJson {
  /**
   * Maps patch directory to source tree directory
   *
   * This interface was referenced by `JSONSchemaForElectronPatchesConfigJson`'s JSON-Schema definition
   * via the `patternProperty` "^src/electron/".
   */
  [k: string]: string;
}
