/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type JSONSchemaForEVMConfigurationFiles = {
  $schema?: string;
  /**
   * Default build target
   */
  defaultTarget?: string;
  /**
   * Preserve the N most recent Xcode SDK versions
   */
  preserveSDK?: number;
  /**
   * Name of the built executable to run
   */
  execName?: string;
  /**
   * Name of base config to extend
   */
  extends?: string;
  /**
   * Whether to use the Electron RBE infrastructure
   */
  reclient?: "remote_exec" | "none";
  /**
   * Path to alternative reclient credential helper
   */
  reclientHelperPath?: string;
  /**
   * Alternative RBE cluster address
   */
  reclientServiceAddress?: string;
  /**
   * Path of the top directory. Home of the .gclient file
   */
  root?: string;
  /**
   * Remotes for Git checkouts
   */
  remotes?: {
    /**
     * Remotes for the Electron repo
     */
    electron: {
      /**
       * Fork remote
       */
      fork?: {
        [k: string]: unknown;
      } & string;
      /**
       * Origin remote
       */
      origin: {
        [k: string]: unknown;
      } & string;
    };
  };
  /**
   * Configuration for GN
   */
  gen?: {
    /**
     * Extra arguments for GN
     */
    args: string[];
    /**
     * Output directory
     */
    out: string;
  };
  /**
   * Environment variables set when building Electron
   */
  env?: {
    /**
     * Path to use as git cache for gclient
     */
    GIT_CACHE_PATH?: string;
    /**
     * Path of Chromium buildtools in the checkout
     */
    CHROMIUM_BUILDTOOLS_PATH: string;
    [k: string]: unknown;
  };
  /**
   * Validation level for this configuration
   */
  configValidationLevel?: "strict" | "warn" | "none";
} & (
  | {
      [k: string]: unknown;
    }
  | {
      defaultTarget: string;
      [k: string]: unknown;
    }
);
