/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface JSONSchemaForEVMConfigurationFiles {
  /**
   * Default build target
   */
  defaultTarget?:
    | "breakpad"
    | "chromedriver"
    | "electron"
    | "electron:dist"
    | "mksnapshot"
    | "node:headers";
  /**
   * Goma mode to use
   */
  goma: "cache-only" | "cluster" | "none";
  /**
   * Path of the top directory. Home of the .gclient file
   */
  root: string;
  /**
   * Remotes for Git checkouts
   */
  remotes: {
    /**
     * Remotes for the Electron repo
     */
    electron: {
      /**
       * Fork remote
       */
      fork?: string;
      /**
       * Origin remote
       */
      origin: string;
      [k: string]: unknown;
    };
    /**
     * Remotes for the Node repo
     */
    node: {
      /**
       * Origin remote
       */
      origin?: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Configuration for GN
   */
  gen: {
    /**
     * Extra arguments for GN
     */
    args: string[];
    /**
     * Output directory
     */
    out: string;
    [k: string]: unknown;
  };
  /**
   * Environment variables set when building Electron
   */
  env: {
    /**
     * Path to use as git cache for gclient
     */
    GIT_CACHE_PATH?: string;
    /**
     * Path of Chromium buildtools in the checkout
     */
    CHROMIUM_BUILDTOOLS_PATH: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
