/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * When building, show a list of build targets to choose from.
 */
export type ShowTargets = boolean;
/**
 * Lint relative links in the docs and mark broken links as problems.
 */
export type LintRelativeLinks = boolean;
/**
 * When syncing, use three-way merge.
 */
export type ThreeWayMerge = boolean;

export interface ElectronBuildTools {
  "electronBuildTools.build.buildOptions"?: BuildOptions;
  /**
   * Default target to build. Leave blank to use the config default.
   */
  "electronBuildTools.build.defaultTarget"?:
    | "----"
    | "third_party/breakpad:dump_syms"
    | "electron:electron_chromedriver_zip"
    | "electron"
    | "electron:electron_dist_zip"
    | "electron:electron_mksnapshot_zip"
    | "electron:node_headers";
  "electronBuildTools.build.ninjaArgs"?: NinjaArgs;
  "electronBuildTools.build.showTargets"?: ShowTargets;
  "electronBuildTools.docs.lintRelativeLinks"?: LintRelativeLinks;
  "electronBuildTools.sync.threeWayMerge"?: ThreeWayMerge;
  [k: string]: unknown;
}
/**
 * Options to use when building.
 */
export interface BuildOptions {
  /**
   * Build without remote execution (entirely locally).
   */
  "--no-remote"?: "";
  /**
   * Force a re-run of `gn gen` before building.
   */
  "--gen"?: "";
  /**
   * Forces a specific ninja target.
   */
  "--target"?: string;
  [k: string]: string;
}
/**
 * Args to pass to Ninja when building.
 */
export interface NinjaArgs {
  [k: string]: string;
}
