/* eslint-disable @typescript-eslint/naming-convention */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * When building, show a list of build targets to choose from.
 */
export type ShowTargets = boolean;
/**
 * Lint relative links in the docs and mark broken links as problems.
 */
export type LintRelativeLinks = boolean;

export interface ElectronBuildTools {
  "electronBuildTools.build.buildOptions"?: BuildOptions;
  /**
   * Default target to build. Leave blank to use the config default.
   */
  "electronBuildTools.build.defaultTarget"?:
    | "----"
    | "breakpad"
    | "chromedriver"
    | "electron"
    | "electron:dist"
    | "mksnapshot"
    | "node:headers";
  "electronBuildTools.build.ninjaArgs"?: NinjaArgs;
  "electronBuildTools.build.showTargets"?: ShowTargets;
  /**
   * Executable to use for running `build-tools` commands.
   */
  "electronBuildTools.buildTools.executable"?: "electron-build-tools" | "e";
  "electronBuildTools.docs.lintRelativeLinks"?: LintRelativeLinks;
  [k: string]: unknown;
}
/**
 * Options to use when building.
 */
export interface BuildOptions {
  /**
   * Build without goma.
   */
  "--no-goma"?: "";
  /**
   * Force a re-run of `gn gen` before building.
   */
  "--gen"?: "";
  /**
   * Forces a specific ninja target.
   */
  "--target"?: string;
  [k: string]: unknown;
}
/**
 * Args to pass to Ninja when building.
 */
export interface NinjaArgs {
  [k: string]: string;
}
